version: '3'
 
services:
    cassandra:
        image: cassandra:3.11.2
        container_name: cassandra
        ports:
            - "9042:9042"
        environment:
            - "MAX_HEAP_SIZE=256M"
            - "HEAP_NEWSIZE=128M"
        restart: always
        networks:
            - backend
        healthcheck:
            test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
            interval: 20s
            timeout: 10s
            retries: 10
 
    cassandra-load-keyspace:
        container_name: cassandra-load-keyspace
        image: cassandra:3.11.2
        depends_on:
            cassandra:
                condition: service_healthy
        networks:
            - backend
        volumes:
            - ./cassandra_schema.cql:/schema.cql
        command: /bin/bash -c "echo Loading cassandra keyspace... && cqlsh cassandra -f /schema.cql"
 
networks:
    backend:
        driver: bridge
